# Generated by Django 3.2.3 on 2022-03-10 17:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True, verbose_name='Имя пользователя')),
                ('email', models.CharField(max_length=200, verbose_name='Почта')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ordered', models.DateTimeField(auto_now_add=True, verbose_name='Дата оформления заказа')),
                ('complete', models.BooleanField(default=False, verbose_name='Статус')),
                ('transaction_id', models.CharField(max_length=100, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название книги')),
                ('description', models.TextField(verbose_name='Описание книги')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('availability', models.BooleanField(default=False, verbose_name='Наличие')),
                ('group', models.CharField(choices=[('Юмор', 'Юмор'), ('Документальная литература', 'Документальная литература'), ('Учебная книга', 'Учебная книга'), ('Деловая литература', 'Деловая литература'), ('Религиозная литература', 'Религиозная литература'), ('Научная книга', 'Научная книга'), ('Детектив', 'Детектив'), ('Приключения', 'Приключения'), ('Книги о психологии', 'Книги о психологии'), ('Детская книга', 'Детская книга'), ('Хобби', 'Хобби'), ('Справочная книга', 'Справочная книга'), ('Фольклор', 'Фольклор'), ('Фантастика', 'Фантастика'), ('Поэзия', 'Поэзия'), ('Зарубежная', 'Зарубежная'), ('Роман', 'Роман'), ('Техника', 'Техника')], default='Детектив', max_length=100, verbose_name='Жанр')),
                ('img', models.ImageField(default='Books_Shop_Site/no_image.jpg', upload_to='Books_Shop_Site/product_image', verbose_name='Обложка')),
                ('author', models.CharField(max_length=256, verbose_name='Автор книги')),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
            },
        ),
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('zipcode', models.CharField(max_length=200)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.customer')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.order')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.order')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.product')),
            ],
        ),
    ]
